# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My regular naggy posts
email: &email jelf.personal@zoho.eu
description: >
  A blog about ruby / haskell / webdev. Mostly in russian
baseurl: ""
url: "https://jelf.github.io"

twitter:
  username: &twitter_username BruOverseer
twitter_username: *twitter_username
github_username:  jelf
timezone: Europe/Moscow

google_analytics: UA-105581925-1

author: JelF <jelf.personal@zoho.eu>

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .envrc
  - bin/
